export ASR_DECODER_SERVER=funasr_triton
export ASR_DECODER_SERVER_URI=127.0.0.1:8001
export VAD_GPU=False
export ASR_VAD_MAX=15000
export TZ=Asia/Shanghai
export ASR_API_HOST=0.0.0.0
export ASR_API_URL_DB=tmp/d9/url.db
export ASR_API_PORT=8304
export ASR_API_CONCURRENCY=100
asr_api_server  | tee callback-`date --iso-8601=seconds`.log
